### ISSUE TITLE
character panel in the upper left corner

### ISSUE THREAD

**Issue by Fearrow** [joker-119/Roth_UI#13]
character panel in the upper left corner. at the entrance to the RAID the same panel open to all members of the RAID, filling the whole screen, superimposed on each other when there is not enough space vertically. How do I disable this display for groups and raids?
![tt](https://user-images.githubusercontent.com/43406493/45748210-ba8b7380-bc10-11e8-9152-47e124198c1e.jpg)

**Comment by joker-119** [comment]
This shouldn't really happen, but may be caused by your screen resolution (or physical size of your screen) being significantly smaller than what the add on defaults to. You can move the overlapping frames with /roth unlockunits

You can disable raid frames in the config.lua file under - - RAID set show=true to show=false
