### ISSUE TITLE
Addon package does not use SavedVariables to store user state

### ISSUE THREAD

**Issue by DianeOfTheMoon** [joker-119/Roth_UI#4]
As a user, I'd like to have my layout and configuration preserved between updates.  This includes positioning, font style and sizes, and what items I have enabled/disabled.  When this is completed, I should be able to edit common settings via an addon panel, and updates to the addon suite should not overwrite the settings unless needed for backwards incompatible changes.

**Comment by DianeOfTheMoon** [comment]
@galaxy119 , I _can_ work on this, but currently am afraid to due to not understanding how you're developing or if you'll even take outside pull requests.  Can you let me know?

**Comment by joker-119** [comment]
After my release today (1.9.14) I don't have plans on releasing another update for some time, due to time constraints IRL, I can really only dedicate myself to fixing critical bugs at this point, as of 1.9.14, all of my 'planned features' are implemented and working (as far as I've been able to test myself).

I WILL accept pull requests, and would more than welcome your work on the addon, your work on centralizing the font strings was very nice, the only reason i didn't accept it was I was already done with and pushing my centralization instead, with the includement of RothFont.

I would love for a feature such as this, however I simply do not have the time to implement it myself. 
If you would like to work on this, I'd be more than happy to merge your pull request(s) into the master.

You can contact me in-game at Galaxy119#1463 if you like, I'm not always doing stuff but I'm usually on bnet or sitting in-game chatting while I work on RL stuff.

Also, on a note from your previous pull request - globals are not likely the best idea, you should be able to simply pull all of the information from the config.lua file into a database, have all the config options point to the database first, using the config file as the "default" values for anything missing, like what is done in the core/panel.lua and core/db.lua file for the orbs.
You can likely use the orb config panel as a base to get you started on moving everything from the config.lua file into a panel aswell, or expanding the orb panel itself to include those options.

Remember; Rework, reuse, recycle

**Comment by DianeOfTheMoon** [comment]
Added sub-issue:
Allow user customization of system fonts. https://github.com/galaxy119/Roth_UI/issues/5
